<?php

/**
 * @file
 * Allows Better Configuration of Contact forms.
 */


/**
 * Implements hook_mail_alter()
 */
function better_contact_mail_alter(&$message){

  unset($message['headers']['Sender']);
  unset($message['headers']['Errors-To']);
  unset($message['headers']['Return-Path']);
 
 
  if ($message['id'] == 'contact_user_mail') {
    $message['subject'] = substr($message['subject'],34);
    /* strip out preamble added by contact form */
    array_splice($message['body'],0,4);
	array_push ($message['body'], "This message was sent from your pesonal contact form on libraries.ou.edu");
  }
  
  

}
